import type { Metadata } from "next";
import { Gothic_A1 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const gothicA1 = Gothic_A1({
  variable: "--font-gothic-a1",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothicA1.variable}  antialiased`}>
        <div className="relative bg-[url('/bg/space_bg.gif')] bg-cover bg-center bg-no-repeat overflow-hidden">
  <Navbar />
  {children}
</div>

      </body>
    </html>
  );
}
